/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as DashboardStatusPagesRouteImport } from './routes/_dashboard/status-pages'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardLogsRouteImport } from './routes/_dashboard/logs'
import { Route as DashboardIncidentsRouteImport } from './routes/_dashboard/incidents'
import { Route as DashboardAlertsRouteImport } from './routes/_dashboard/alerts'
import { Route as AuthPathnameIndexRouteImport } from './routes/auth/$pathname/index'
import { Route as DashboardMonitorsMonitorIdRouteImport } from './routes/_dashboard/monitors.$monitorId'

const DashboardIndexLazyRouteImport = createFileRoute('/_dashboard/')()
const DashboardMonitorsIndexLazyRouteImport = createFileRoute(
  '/_dashboard/monitors/',
)()

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexLazyRoute = DashboardIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/index.lazy').then((d) => d.Route),
)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStatusPagesRoute = DashboardStatusPagesRouteImport.update({
  id: '/status-pages',
  path: '/status-pages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/settings.lazy').then((d) => d.Route),
)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIncidentsRoute = DashboardIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitorsIndexLazyRoute =
  DashboardMonitorsIndexLazyRouteImport.update({
    id: '/monitors/',
    path: '/monitors/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/monitors/index.lazy').then((d) => d.Route),
  )
const AuthPathnameIndexRoute = AuthPathnameIndexRouteImport.update({
  id: '/auth/$pathname/',
  path: '/auth/$pathname/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMonitorsMonitorIdRoute =
  DashboardMonitorsMonitorIdRouteImport.update({
    id: '/monitors/$monitorId',
    path: '/monitors/$monitorId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexLazyRoute
  '/alerts': typeof DashboardAlertsRoute
  '/incidents': typeof DashboardIncidentsRoute
  '/logs': typeof DashboardLogsRoute
  '/settings': typeof DashboardSettingsRoute
  '/status-pages': typeof DashboardStatusPagesRoute
  '/account/settings': typeof AccountSettingsRoute
  '/monitors/$monitorId': typeof DashboardMonitorsMonitorIdRoute
  '/auth/$pathname/': typeof AuthPathnameIndexRoute
  '/monitors/': typeof DashboardMonitorsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/alerts': typeof DashboardAlertsRoute
  '/incidents': typeof DashboardIncidentsRoute
  '/logs': typeof DashboardLogsRoute
  '/settings': typeof DashboardSettingsRoute
  '/status-pages': typeof DashboardStatusPagesRoute
  '/account/settings': typeof AccountSettingsRoute
  '/': typeof DashboardIndexLazyRoute
  '/monitors/$monitorId': typeof DashboardMonitorsMonitorIdRoute
  '/auth/$pathname': typeof AuthPathnameIndexRoute
  '/monitors': typeof DashboardMonitorsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/alerts': typeof DashboardAlertsRoute
  '/_dashboard/incidents': typeof DashboardIncidentsRoute
  '/_dashboard/logs': typeof DashboardLogsRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/status-pages': typeof DashboardStatusPagesRoute
  '/account/settings': typeof AccountSettingsRoute
  '/_dashboard/': typeof DashboardIndexLazyRoute
  '/_dashboard/monitors/$monitorId': typeof DashboardMonitorsMonitorIdRoute
  '/auth/$pathname/': typeof AuthPathnameIndexRoute
  '/_dashboard/monitors/': typeof DashboardMonitorsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/incidents'
    | '/logs'
    | '/settings'
    | '/status-pages'
    | '/account/settings'
    | '/monitors/$monitorId'
    | '/auth/$pathname/'
    | '/monitors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alerts'
    | '/incidents'
    | '/logs'
    | '/settings'
    | '/status-pages'
    | '/account/settings'
    | '/'
    | '/monitors/$monitorId'
    | '/auth/$pathname'
    | '/monitors'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/alerts'
    | '/_dashboard/incidents'
    | '/_dashboard/logs'
    | '/_dashboard/settings'
    | '/_dashboard/status-pages'
    | '/account/settings'
    | '/_dashboard/'
    | '/_dashboard/monitors/$monitorId'
    | '/auth/$pathname/'
    | '/_dashboard/monitors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AccountSettingsRoute: typeof AccountSettingsRoute
  AuthPathnameIndexRoute: typeof AuthPathnameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/status-pages': {
      id: '/_dashboard/status-pages'
      path: '/status-pages'
      fullPath: '/status-pages'
      preLoaderRoute: typeof DashboardStatusPagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/logs': {
      id: '/_dashboard/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/incidents': {
      id: '/_dashboard/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof DashboardIncidentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/alerts': {
      id: '/_dashboard/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/monitors/': {
      id: '/_dashboard/monitors/'
      path: '/monitors'
      fullPath: '/monitors/'
      preLoaderRoute: typeof DashboardMonitorsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/$pathname/': {
      id: '/auth/$pathname/'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname/'
      preLoaderRoute: typeof AuthPathnameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/monitors/$monitorId': {
      id: '/_dashboard/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/monitors/$monitorId'
      preLoaderRoute: typeof DashboardMonitorsMonitorIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardIncidentsRoute: typeof DashboardIncidentsRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStatusPagesRoute: typeof DashboardStatusPagesRoute
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
  DashboardMonitorsMonitorIdRoute: typeof DashboardMonitorsMonitorIdRoute
  DashboardMonitorsIndexLazyRoute: typeof DashboardMonitorsIndexLazyRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardIncidentsRoute: DashboardIncidentsRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStatusPagesRoute: DashboardStatusPagesRoute,
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
  DashboardMonitorsMonitorIdRoute: DashboardMonitorsMonitorIdRoute,
  DashboardMonitorsIndexLazyRoute: DashboardMonitorsIndexLazyRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AccountSettingsRoute: AccountSettingsRoute,
  AuthPathnameIndexRoute: AuthPathnameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
