/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceIdRouteImport } from './routes/$workspaceId'
import { Route as WorkspaceIdStatusPagesRouteImport } from './routes/$workspaceId/status-pages'
import { Route as WorkspaceIdSettingsRouteImport } from './routes/$workspaceId/settings'
import { Route as WorkspaceIdLogsRouteImport } from './routes/$workspaceId/logs'
import { Route as WorkspaceIdIncidentsRouteImport } from './routes/$workspaceId/incidents'
import { Route as WorkspaceIdAlertsRouteImport } from './routes/$workspaceId/alerts'
import { Route as WorkspaceIdMonitorsMonitorIdRouteImport } from './routes/$workspaceId/monitors.$monitorId'

const IndexLazyRouteImport = createFileRoute('/')()
const WorkspaceIdIndexLazyRouteImport = createFileRoute('/$workspaceId/')()
const AuthPathnameIndexLazyRouteImport = createFileRoute('/auth/$pathname/')()
const WorkspaceIdMonitorsIndexLazyRouteImport = createFileRoute(
  '/$workspaceId/monitors/',
)()

const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const WorkspaceIdIndexLazyRoute = WorkspaceIdIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceIdRoute,
} as any).lazy(() =>
  import('./routes/$workspaceId/index.lazy').then((d) => d.Route),
)
const WorkspaceIdStatusPagesRoute = WorkspaceIdStatusPagesRouteImport.update({
  id: '/status-pages',
  path: '/status-pages',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdSettingsRoute = WorkspaceIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceIdRoute,
} as any).lazy(() =>
  import('./routes/$workspaceId/settings.lazy').then((d) => d.Route),
)
const WorkspaceIdLogsRoute = WorkspaceIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdIncidentsRoute = WorkspaceIdIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdAlertsRoute = WorkspaceIdAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const AuthPathnameIndexLazyRoute = AuthPathnameIndexLazyRouteImport.update({
  id: '/auth/$pathname/',
  path: '/auth/$pathname/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/$pathname/index.lazy').then((d) => d.Route),
)
const WorkspaceIdMonitorsIndexLazyRoute =
  WorkspaceIdMonitorsIndexLazyRouteImport.update({
    id: '/monitors/',
    path: '/monitors/',
    getParentRoute: () => WorkspaceIdRoute,
  } as any).lazy(() =>
    import('./routes/$workspaceId/monitors/index.lazy').then((d) => d.Route),
  )
const WorkspaceIdMonitorsMonitorIdRoute =
  WorkspaceIdMonitorsMonitorIdRouteImport.update({
    id: '/monitors/$monitorId',
    path: '/monitors/$monitorId',
    getParentRoute: () => WorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$workspaceId': typeof WorkspaceIdRouteWithChildren
  '/$workspaceId/alerts': typeof WorkspaceIdAlertsRoute
  '/$workspaceId/incidents': typeof WorkspaceIdIncidentsRoute
  '/$workspaceId/logs': typeof WorkspaceIdLogsRoute
  '/$workspaceId/settings': typeof WorkspaceIdSettingsRoute
  '/$workspaceId/status-pages': typeof WorkspaceIdStatusPagesRoute
  '/$workspaceId/': typeof WorkspaceIdIndexLazyRoute
  '/$workspaceId/monitors/$monitorId': typeof WorkspaceIdMonitorsMonitorIdRoute
  '/$workspaceId/monitors/': typeof WorkspaceIdMonitorsIndexLazyRoute
  '/auth/$pathname/': typeof AuthPathnameIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$workspaceId/alerts': typeof WorkspaceIdAlertsRoute
  '/$workspaceId/incidents': typeof WorkspaceIdIncidentsRoute
  '/$workspaceId/logs': typeof WorkspaceIdLogsRoute
  '/$workspaceId/settings': typeof WorkspaceIdSettingsRoute
  '/$workspaceId/status-pages': typeof WorkspaceIdStatusPagesRoute
  '/$workspaceId': typeof WorkspaceIdIndexLazyRoute
  '/$workspaceId/monitors/$monitorId': typeof WorkspaceIdMonitorsMonitorIdRoute
  '/$workspaceId/monitors': typeof WorkspaceIdMonitorsIndexLazyRoute
  '/auth/$pathname': typeof AuthPathnameIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/$workspaceId': typeof WorkspaceIdRouteWithChildren
  '/$workspaceId/alerts': typeof WorkspaceIdAlertsRoute
  '/$workspaceId/incidents': typeof WorkspaceIdIncidentsRoute
  '/$workspaceId/logs': typeof WorkspaceIdLogsRoute
  '/$workspaceId/settings': typeof WorkspaceIdSettingsRoute
  '/$workspaceId/status-pages': typeof WorkspaceIdStatusPagesRoute
  '/$workspaceId/': typeof WorkspaceIdIndexLazyRoute
  '/$workspaceId/monitors/$monitorId': typeof WorkspaceIdMonitorsMonitorIdRoute
  '/$workspaceId/monitors/': typeof WorkspaceIdMonitorsIndexLazyRoute
  '/auth/$pathname/': typeof AuthPathnameIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspaceId'
    | '/$workspaceId/alerts'
    | '/$workspaceId/incidents'
    | '/$workspaceId/logs'
    | '/$workspaceId/settings'
    | '/$workspaceId/status-pages'
    | '/$workspaceId/'
    | '/$workspaceId/monitors/$monitorId'
    | '/$workspaceId/monitors/'
    | '/auth/$pathname/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$workspaceId/alerts'
    | '/$workspaceId/incidents'
    | '/$workspaceId/logs'
    | '/$workspaceId/settings'
    | '/$workspaceId/status-pages'
    | '/$workspaceId'
    | '/$workspaceId/monitors/$monitorId'
    | '/$workspaceId/monitors'
    | '/auth/$pathname'
  id:
    | '__root__'
    | '/'
    | '/$workspaceId'
    | '/$workspaceId/alerts'
    | '/$workspaceId/incidents'
    | '/$workspaceId/logs'
    | '/$workspaceId/settings'
    | '/$workspaceId/status-pages'
    | '/$workspaceId/'
    | '/$workspaceId/monitors/$monitorId'
    | '/$workspaceId/monitors/'
    | '/auth/$pathname/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  WorkspaceIdRoute: typeof WorkspaceIdRouteWithChildren
  AuthPathnameIndexLazyRoute: typeof AuthPathnameIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$workspaceId': {
      id: '/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/$workspaceId'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId/': {
      id: '/$workspaceId/'
      path: '/'
      fullPath: '/$workspaceId/'
      preLoaderRoute: typeof WorkspaceIdIndexLazyRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/status-pages': {
      id: '/$workspaceId/status-pages'
      path: '/status-pages'
      fullPath: '/$workspaceId/status-pages'
      preLoaderRoute: typeof WorkspaceIdStatusPagesRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/settings': {
      id: '/$workspaceId/settings'
      path: '/settings'
      fullPath: '/$workspaceId/settings'
      preLoaderRoute: typeof WorkspaceIdSettingsRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/logs': {
      id: '/$workspaceId/logs'
      path: '/logs'
      fullPath: '/$workspaceId/logs'
      preLoaderRoute: typeof WorkspaceIdLogsRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/incidents': {
      id: '/$workspaceId/incidents'
      path: '/incidents'
      fullPath: '/$workspaceId/incidents'
      preLoaderRoute: typeof WorkspaceIdIncidentsRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/alerts': {
      id: '/$workspaceId/alerts'
      path: '/alerts'
      fullPath: '/$workspaceId/alerts'
      preLoaderRoute: typeof WorkspaceIdAlertsRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/auth/$pathname/': {
      id: '/auth/$pathname/'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname/'
      preLoaderRoute: typeof AuthPathnameIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId/monitors/': {
      id: '/$workspaceId/monitors/'
      path: '/monitors'
      fullPath: '/$workspaceId/monitors/'
      preLoaderRoute: typeof WorkspaceIdMonitorsIndexLazyRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/monitors/$monitorId': {
      id: '/$workspaceId/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/$workspaceId/monitors/$monitorId'
      preLoaderRoute: typeof WorkspaceIdMonitorsMonitorIdRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
  }
}

interface WorkspaceIdRouteChildren {
  WorkspaceIdAlertsRoute: typeof WorkspaceIdAlertsRoute
  WorkspaceIdIncidentsRoute: typeof WorkspaceIdIncidentsRoute
  WorkspaceIdLogsRoute: typeof WorkspaceIdLogsRoute
  WorkspaceIdSettingsRoute: typeof WorkspaceIdSettingsRoute
  WorkspaceIdStatusPagesRoute: typeof WorkspaceIdStatusPagesRoute
  WorkspaceIdIndexLazyRoute: typeof WorkspaceIdIndexLazyRoute
  WorkspaceIdMonitorsMonitorIdRoute: typeof WorkspaceIdMonitorsMonitorIdRoute
  WorkspaceIdMonitorsIndexLazyRoute: typeof WorkspaceIdMonitorsIndexLazyRoute
}

const WorkspaceIdRouteChildren: WorkspaceIdRouteChildren = {
  WorkspaceIdAlertsRoute: WorkspaceIdAlertsRoute,
  WorkspaceIdIncidentsRoute: WorkspaceIdIncidentsRoute,
  WorkspaceIdLogsRoute: WorkspaceIdLogsRoute,
  WorkspaceIdSettingsRoute: WorkspaceIdSettingsRoute,
  WorkspaceIdStatusPagesRoute: WorkspaceIdStatusPagesRoute,
  WorkspaceIdIndexLazyRoute: WorkspaceIdIndexLazyRoute,
  WorkspaceIdMonitorsMonitorIdRoute: WorkspaceIdMonitorsMonitorIdRoute,
  WorkspaceIdMonitorsIndexLazyRoute: WorkspaceIdMonitorsIndexLazyRoute,
}

const WorkspaceIdRouteWithChildren = WorkspaceIdRoute._addFileChildren(
  WorkspaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  WorkspaceIdRoute: WorkspaceIdRouteWithChildren,
  AuthPathnameIndexLazyRoute: AuthPathnameIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
